# Menu API

###
# baseURL
@baseURL = https://eater-api.herokuapp.com
@token = "TODO"


###
# Get Menu for date range
@startDate = 2022-04-01
@endDate = 2022-04-07
GET {{baseURL}}/menu?startDate={{startDate}}&endDate={{endDate}}
Authorization: "Bearer {{token}}"

###
# Get Menu for a day
@date = 2021-10-27
GET {{baseURL}}/menu/details?date={{date}}
Authorization: "Bearer {{token}}"


###
# Create Menu item
POST {{baseURL}}/menu
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "date": "2022-04-05",
    "portions": 1,
    "recipeId": "984fb97f-ce9e-4f75-82b4-f8ffe7458423"
}

###
# Edit Menu item
PUT {{baseURL}}/menu/aa283065-3816-4261-8a64-bba86bb67aaa
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "portions": 4,
    "recipeId": "6bd19b1c-5201-4e32-a5c4-4d20956ce2c0"
}

###
# Delere Recipe By Id
DELETE {{baseURL}}/menu/aa283065-3816-4261-8a64-bba86bb67aaa
Authorization: "Bearer {{token}}"