# Menu API

###
# baseURL
@baseURL = http://localhost:3000
@sess = TODO
@sig = TODO
@cookie = google-auth-session={{sess}}; google-auth-session.sig={{sig}}

###
# Get Menu for date range
@startDate = 2021-10-25
@endDate = 2021-10-27
GET {{baseURL}}/menu?startDate={{startDate}}&endDate={{endDate}}
Cookie: {{cookie}}

###
# Get Menu for a day
@date = 2021-10-27
GET {{baseURL}}/menu/details?date={{date}}
Cookie: {{cookie}}


###
# Create Menu item
POST {{baseURL}}/menu
Content-Type: application/json
Cookie: {{cookie}}

{
    "date": "2021-10-27",
    "portions": 1,
    "recipeId": "6bd19b1c-5201-4e32-a5c4-4d20956ce2c0"
}

###
# Edit Menu item
PUT {{baseURL}}/menu/aa283065-3816-4261-8a64-bba86bb67aaa
Content-Type: application/json
Cookie: {{cookie}}

{
    "portions": 4,
    "recipeId": "6bd19b1c-5201-4e32-a5c4-4d20956ce2c0"
}

###
# Delere Recipe By Id
DELETE {{baseURL}}/menu/aa283065-3816-4261-8a64-bba86bb67aaa
Cookie: {{cookie}}