# Recipes API

###
# baseURL
@baseURL = https://eater-api.herokuapp.com
@token = "TODO"

###
# Find All Recipes
GET {{baseURL}}/recipes
Authorization: "Bearer {{token}}"

###
# Find Recipe By Id
GET {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Authorization: "Bearer {{token}}"


###
# Add Recipe
POST {{baseURL}}/recipes
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "name": "name 2",
    "description": "description 2",
    "graphicURL": "url",
    "ingredients": [
        {
            "name": "ingredient 2",
            "amount": 1.0,
            "measure": "piece"
        },
        {
            "name": "ingredient 3",
            "amount": 0.5,
            "measure": "kg"
        }
    ]
}

###
# Edit Recipe By Id
PUT {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "name": "updated name",
    "description": "description",
    "graphicURL": "url",
    "ingredients": [
        {
            "name": "ingredient 2",
            "amount": 3,
            "measure": "piece"
        },
        {
            "name": "ingredient 3",
            "amount": 0.5,
            "measure": "kg"
        }
    ]
}

###
# Delere Recipe By Id
DELETE {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Authorization: "Bearer {{token}}"