# Recipes API

###
# baseURL
@baseURL = http://localhost:3000
@sess = TODO
@sig = TODO
@cookie = google-auth-session={{sess}}; google-auth-session.sig={{sig}}

###
# Find All Recipes
GET {{baseURL}}/recipes
Cookie: {{cookie}}

###
# Find Recipe By Id
GET {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Cookie: {{cookie}}


###
# Add Recipe
POST {{baseURL}}/recipes
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "name 2",
    "description": "description 2",
    "graphicURL": "url",
    "ingredients": [
        {
            "name": "ingredient 2",
            "amount": 1.0,
            "measure": "piece"
        },
        {
            "name": "ingredient 3",
            "amount": 0.5,
            "measure": "kg"
        }
    ]
}

###
# Edit Recipe By Id
PUT {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "updated name",
    "description": "description",
    "graphicURL": "url",
    "ingredients": [
        {
            "name": "ingredient 2",
            "amount": 3,
            "measure": "piece"
        },
        {
            "name": "ingredient 3",
            "amount": 0.5,
            "measure": "kg"
        }
    ]
}

###
# Delere Recipe By Id
DELETE {{baseURL}}/recipes/e64064a6-4637-4fbe-84b3-70b89c45c566
Cookie: {{cookie}}