# Menu API

###
# baseURL

@baseURL = https://eater-api.herokuapp.com
@token = "TODO"

###
# List Shopping Lists 
GET {{baseURL}}/shopping-list
Authorization: "Bearer {{token}}"

###
# Get Shopping List
GET {{baseURL}}/shopping-list/81608dda-4664-4c6a-87d2-ad07fa311bb8
Authorization: "Bearer {{token}}"


###
# Create Shopping List
POST {{baseURL}}/shopping-list
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "startDate": "2021-10-25",
    "endDate": "2021-10-28"
}

###
# Mark Shopping List Item
PUT {{baseURL}}/shopping-list/b57dbaaa-3fe6-4f9b-83d6-e6f888c405c6/item/335d317d-714d-4cff-90de-392587069ccf
Content-Type: application/json
Authorization: "Bearer {{token}}"

{
    "marked": true
}
