# Menu API

###
# baseURL

@baseURL = http://localhost:3000
@sess = TODO
@sig = TODO
@cookie = google-auth-session={{sess}}; google-auth-session.sig={{sig}}

###
# List Shopping Lists 
GET {{baseURL}}/shopping-list
Cookie: {{cookie}}

###
# Get Shopping List
GET {{baseURL}}/shopping-list/2
Cookie: {{cookie}}


###
# Create Shopping List
POST {{baseURL}}/shopping-list
Content-Type: application/json
Cookie: {{cookie}}

{
    "startDate": "2021-10-25",
    "endDate": "2021-10-28"
}

###
# Mark Shopping List Item
PUT {{baseURL}}/shopping-list/6/item/16
Content-Type: application/json
Cookie: {{cookie}}

{
    "marked": true
}
